enable: true

organizationalUnits:
  - name: Security
    organizationalUnits: []
  - name: Infrastructure
    organizationalUnits:
      - name: Network
      - name: SharedServices
  - name: Workloads
    organizationalUnits:
      - name: Dev
      - name: Test
      - name: Prod
  - name: Sandbox
  - name: Suspended

serviceControlPolicies:
  - name: DenyRootUser
    description: Deny root user actions
    policy: service-control-policies/deny-root-user.json
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Workloads
  - name: DenyLeavingOrganization
    description: Prevent accounts from leaving the organization
    policy: service-control-policies/deny-leave-org.json
    deploymentTargets:
      organizationalUnits:
        - Workloads
        - Sandbox
